#!/bin/sh
# Generated by {)tool-name(} using theme {)theme-name(}

font=$(echo "{)font(}" | sed -e 's/-/\\-/g')
$@ -fn "${font}" -nb '#{)base00-hex(}' -sf '#{)base05-hex(}' -sb '#{)base01-hex(}' -nf '#{)base05-hex(}'
